spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=UTC
    username: user
    password: Password@123
    driver-class: com.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true